export const lide = [
	{ id: 1, jmeno: "Patrik", prijmeni: "Moravec", vek: 56, organizacniJednotkaId: 2 },
	{ id: 2, jmeno: "David", prijmeni: "Sedláček", vek: 29, organizacniJednotkaId: 2 },
	{ id: 3, jmeno: "Zuzana", prijmeni: "Urbanová", vek: 35, organizacniJednotkaId: 6 },
	{ id: 4, jmeno: "Jáchym", prijmeni: "Ježek", vek: 26, organizacniJednotkaId: 2 },
	{ id: 5, jmeno: "Jolana", prijmeni: "Říhová", vek: 40, organizacniJednotkaId: 6 },
	{ id: 6, jmeno: "Taťána", prijmeni: "Holubová", vek: 54, organizacniJednotkaId: 4 },
	{ id: 7, jmeno: "Renata", prijmeni: "Fialová", vek: 26, organizacniJednotkaId: 5 },
	{ id: 8, jmeno: "Bedřich", prijmeni: "Havlíček", vek: 43, organizacniJednotkaId: 2 },
	{ id: 9, jmeno: "Vítek", prijmeni: "Stejskal", vek: 57, organizacniJednotkaId: 2 },
	{ id: 10, jmeno: "Vanesa", prijmeni: "Lišková", vek: 40, organizacniJednotkaId: 7 },
	{ id: 11, jmeno: "Květuše", prijmeni: "Říhová", vek: 44, organizacniJednotkaId: 1 },
	{ id: 12, jmeno: "Magda", prijmeni: "Kolářová", vek: 28, organizacniJednotkaId: 5 },
	{ id: 13, jmeno: "Tereza", prijmeni: "Bláhová", vek: 54, organizacniJednotkaId: 5 },
	{ id: 14, jmeno: "Alice", prijmeni: "Pavlíková", vek: 49, organizacniJednotkaId: 7 },
	{ id: 15, jmeno: "Ota", prijmeni: "Valenta", vek: 58, organizacniJednotkaId: 8 },
	{ id: 16, jmeno: "Johana", prijmeni: "Beranová", vek: 52, organizacniJednotkaId: 1 },
	{ id: 17, jmeno: "Jaromír", prijmeni: "Prokop", vek: 31, organizacniJednotkaId: 4 },
	{ id: 18, jmeno: "Johana", prijmeni: "Lišková", vek: 33, organizacniJednotkaId: 5 },
	{ id: 19, jmeno: "Otakar", prijmeni: "Mach", vek: 39, organizacniJednotkaId: 3 },
	{ id: 20, jmeno: "Anežka", prijmeni: "Kučerová", vek: 44, organizacniJednotkaId: 6 },
	{ id: 21, jmeno: "Magdalena", prijmeni: "Slavíková", vek: 58, organizacniJednotkaId: 2 },
	{ id: 22, jmeno: "Maxmilián", prijmeni: "Pavlíček", vek: 40, organizacniJednotkaId: 4 },
	{ id: 23, jmeno: "Klára", prijmeni: "Valentová", vek: 22, organizacniJednotkaId: 7 },
	{ id: 24, jmeno: "Bedřich", prijmeni: "Fišer", vek: 30, organizacniJednotkaId: 2 },
	{ id: 25, jmeno: "Radka", prijmeni: "Pospíšilová", vek: 38, organizacniJednotkaId: 5 },
	{ id: 26, jmeno: "Miloslava", prijmeni: "Černá", vek: 32, organizacniJednotkaId: 8 },
	{ id: 27, jmeno: "Štěpán", prijmeni: "Mareš", vek: 30, organizacniJednotkaId: 7 },
	{ id: 28, jmeno: "Božena", prijmeni: "Horáčková", vek: 56, organizacniJednotkaId: 6 },
	{ id: 29, jmeno: "Vlasta", prijmeni: "Ježková", vek: 42, organizacniJednotkaId: 2 },
	{ id: 30, jmeno: "Břetislav", prijmeni: "Beran", vek: 48, organizacniJednotkaId: 7 },
	{ id: 31, jmeno: "Patricie", prijmeni: "Němcová", vek: 55, organizacniJednotkaId: 2 },
	{ id: 32, jmeno: "Sebastian", prijmeni: "Macháček", vek: 29, organizacniJednotkaId: 1 },
	{ id: 33, jmeno: "Libor", prijmeni: "Vaněk", vek: 50, organizacniJednotkaId: 5 },
	{ id: 34, jmeno: "Miloslava", prijmeni: "Němcová", vek: 49, organizacniJednotkaId: 1 },
	{ id: 35, jmeno: "Bedřich", prijmeni: "Čermák", vek: 23, organizacniJednotkaId: 5 },
	{ id: 36, jmeno: "Kateřina", prijmeni: "Pospíšilová", vek: 36, organizacniJednotkaId: 1 },
	{ id: 37, jmeno: "Alexandr", prijmeni: "Vaněk", vek: 29, organizacniJednotkaId: 7 },
	{ id: 38, jmeno: "Karla", prijmeni: "Hrušková", vek: 20, organizacniJednotkaId: 5 },
	{ id: 39, jmeno: "Markéta", prijmeni: "Černá", vek: 44, organizacniJednotkaId: 4 },
	{ id: 40, jmeno: "Michal", prijmeni: "Bureš", vek: 41, organizacniJednotkaId: 3 },
	{ id: 41, jmeno: "Aleš", prijmeni: "Novák", vek: 23, organizacniJednotkaId: 4 },
	{ id: 42, jmeno: "Vojtěch", prijmeni: "Kopecký", vek: 45, organizacniJednotkaId: 1 },
	{ id: 43, jmeno: "Karla", prijmeni: "Vaňková", vek: 44, organizacniJednotkaId: 1 },
	{ id: 44, jmeno: "Svatopluk", prijmeni: "Brož", vek: 43, organizacniJednotkaId: 8 },
	{ id: 45, jmeno: "Ondrej", prijmeni: "Šťastný", vek: 42, organizacniJednotkaId: 1 },
	{ id: 46, jmeno: "Tibor", prijmeni: "Bednář", vek: 56, organizacniJednotkaId: 6 },
	{ id: 47, jmeno: "Karolína", prijmeni: "Benešová", vek: 31, organizacniJednotkaId: 5 },
	{ id: 48, jmeno: "Čestmír", prijmeni: "Vítek", vek: 51, organizacniJednotkaId: 5 },
	{ id: 49, jmeno: "Leopold", prijmeni: "Procházka", vek: 51, organizacniJednotkaId: 4 },
	{ id: 50, jmeno: "Štěpán", prijmeni: "Němec", vek: 41, organizacniJednotkaId: 5 },
];

export const organizacniJednotky = [
	{ id: 1, nazev: "Vývoj" },
	{ id: 2, nazev: "Obchod" },
	{ id: 3, nazev: "Marketing" },
	{ id: 4, nazev: "Výzkum" },
	{ id: 5, nazev: "Design" },
	{ id: 6, nazev: "Účetnictví" },
	{ id: 7, nazev: "Lidské zdroje" },
	{ id: 8, nazev: "Péče o zákazníky" },
];
